name = "nation-path"
main = ".open-next/worker.js"
compatibility_date = "2026-09-24"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "nationpath-media"