name = "nation-path"
main = ".open-next/worker.js"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "NEXT_INC_CACHE_DURABLE_OBJECT"
class_name = "DOShardedTagCache"

[[durable_objects.bindings]]
name = "NEXT_INC_QUEUE_DURABLE_OBJECT"
class_name = "DOQueueHandler"

[exports.DOShardedTagCache]
type = "durable-object"
storage = "sqlite"

[exports.DOQueueHandler]
type = "durable-object"
storage = "sqlite"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "nationpath-media"

[vars]
CONTACT_EMAIL = "info@nationpathindia.com"
NEXT_PUBLIC_BASE_URL = "https://nationpathindia.com"
R2_ACCOUNT_ID = "f0fde36ad591698670ce20c2e798494e"
R2_BUCKET_NAME = "nationpath-media"
R2_PUBLIC_URL = "https://media.nationpathindia.com"
SECURITY_EMAIL = "security@nationpathindia.com"

[observability]
enabled = true
head_sampling_rate = 1
