//////////////////////////////////////////////////////////////
//
// NATIONPATH ASTRO HOROSCOPE
//
// REMEDY INTELLIGENCE TYPES
//
// Production / Future-Proof Contract
//
// Flow:
//
// Astro Intelligence
//      ↓
// Remedy Resolver
//      ↓
// Remedy Language
//      ↓
// Automation
//      ↓
// MongoDB Horoscope
//      ↓
// CMS API
//      ↓
// UI
//
// IMPORTANT:
// - No astronomy
// - No calculations
// - No prediction rules
// - No CMS/database access
// - No automation logic
// - No AI generation
//
//////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////
// REMEDY CATEGORY
//////////////////////////////////////////////////////////////

export type RemedyCategory =
  | "mantra"
  | "puja"
  | "daan"
  | "gemstone"
  | "lifestyle"
  | "other";


//////////////////////////////////////////////////////////////
// REMEDY CONTEXT
//////////////////////////////////////////////////////////////

export interface RemedyContext {

  /**
   * Zodiac sign associated with the
   * current planetary context.
   */
  zodiacSign?: string;

  /**
   * Normalized planet identifier.
   */
  planet?: string;

  /**
   * Already-known planetary strength.
   *
   * This value is NEVER calculated
   * by the remedy layer.
   */
  strengthScore?: number;

  /**
   * Already-known planetary dignity.
   *
   * This value is NEVER calculated
   * by the remedy layer.
   */
  dignity?: string;

  /**
   * Optional remedy category.
   */
  category?: RemedyCategory;

}


//////////////////////////////////////////////////////////////
// REMEDY KNOWLEDGE
//
// Normalized representation of remedy knowledge
// received by the resolver/service layer.
//
// This is KNOWLEDGE DATA.
//
// It is NOT calculated here.
//
// The actual remedy-specific information comes
// from Remedy Intelligence / CMS knowledge.
//////////////////////////////////////////////////////////////

export interface RemedyKnowledge {

  /**
   * Main remedy title/name.
   */
  remedy: string;

  /**
   * Stable remedy identifier.
   */
  slug: string;

  /**
   * Remedy category.
   */
  category: RemedyCategory;

  /**
   * Planets associated with this remedy.
   */
  relatedPlanets?: string[];

  /**
   * Doshas associated with this remedy.
   */
  relatedDoshas?: string[];

  /**
   * Problems/issues associated with this remedy.
   */
  relatedProblems?: string[];

  /**
   * General remedy description.
   */
  description?: string;

  /**
   * Expected/known benefits.
   */
  benefits?: string[];

  /**
   * Practical remedy procedure.
   */
  procedure?: string;

  /**
   * Required materials.
   */
  materials?: string[];

  /**
   * Recommended duration.
   */
  duration?: string;

  /**
   * Precautions.
   */
  precautions?: string[];

  /**
   * Suitable situations/users.
   */
  suitableFor?: string[];

  /**
   * Situations where remedy should be avoided.
   */
  avoidFor?: string[];

  /**
   * Mantra supplied by remedy knowledge.
   *
   * NEVER generated by resolver.
   */
  mantra?: string;

  /**
   * Gemstone information.
   */
  gemstone?: string;

  /**
   * Metal information.
   */
  metal?: string;

  /**
   * Recommended day.
   */
  day?: string;

  /**
   * Associated color.
   */
  color?: string;

  /**
   * Optional media.
   */
  media?: {

    image?: string;

    video?: string;

  };

  /**
   * Optional SEO metadata.
   */
  seo?: {

    title?: string;

    description?: string;

    keywords?: string[];

  };

  /**
   * Publication state.
   */
  status?: "draft" | "published";

}


//////////////////////////////////////////////////////////////
// RESOLVED REMEDY
//
// Final normalized remedy contract.
//
// This object is passed from the resolver
// into language / integration / automation.
//
// IMPORTANT:
//
// Every remedy-specific value originates
// from RemedyKnowledge.
//
// The resolver MUST NOT invent:
//
// - mantra
// - benefit
// - ritual
// - timing
// - gemstone
// - procedure
// - remedy instruction
//
// `reason` is resolver metadata describing
// why the knowledge item matched.
//
// `description` is intentionally preserved because
// the language resolver may use it as a fallback
// when constructing the final remedy language.
//
// Therefore:
//
// RemedyKnowledge.description
//        ↓
// ResolvedRemedy.description
//
//////////////////////////////////////////////////////////////

export interface ResolvedRemedy {

  /**
   * Remedy category.
   */
  category: RemedyCategory;

  /**
   * Normalized remedy title.
   */
  title: string;

  /**
   * Primary practical remedy practice.
   *
   * Usually sourced from procedure,
   * with description as fallback.
   */
  practice: string;

  /**
   * Human-readable remedy guidance.
   *
   * Usually sourced from description,
   * with procedure as fallback.
   */
  guidance: string;

  /**
   * Original/general CMS description.
   *
   * IMPORTANT:
   * This is knowledge data passed through
   * from RemedyKnowledge.
   *
   * It is NOT generated by the resolver.
   */
  description?: string;

  /**
   * Resolver metadata explaining
   * the planetary relevance.
   */
  reason: string;


  ////////////////////////////////////////////////////////////
  // MANTRA
  ////////////////////////////////////////////////////////////

  mantra?: string;


  ////////////////////////////////////////////////////////////
  // BENEFITS
  ////////////////////////////////////////////////////////////

  benefits?: string[];


  ////////////////////////////////////////////////////////////
  // PRECAUTIONS
  ////////////////////////////////////////////////////////////

  precautions?: string[];


  ////////////////////////////////////////////////////////////
  // AVOID FOR
  ////////////////////////////////////////////////////////////

  avoidFor?: string[];


  ////////////////////////////////////////////////////////////
  // SUITABLE FOR
  ////////////////////////////////////////////////////////////

  suitableFor?: string[];


  ////////////////////////////////////////////////////////////
  // MATERIALS
  ////////////////////////////////////////////////////////////

  materials?: string[];


  ////////////////////////////////////////////////////////////
  // DURATION
  ////////////////////////////////////////////////////////////

  duration?: string;


  ////////////////////////////////////////////////////////////
  // GEMSTONE
  ////////////////////////////////////////////////////////////

  gemstone?: string;


  ////////////////////////////////////////////////////////////
  // METAL
  ////////////////////////////////////////////////////////////

  metal?: string;


  ////////////////////////////////////////////////////////////
  // DAY
  ////////////////////////////////////////////////////////////

  day?: string;


  ////////////////////////////////////////////////////////////
  // COLOR
  ////////////////////////////////////////////////////////////

  color?: string;


  ////////////////////////////////////////////////////////////
  // MEDIA
  ////////////////////////////////////////////////////////////

  media?: {

    image?: string;

    video?: string;

  };


  ////////////////////////////////////////////////////////////
  // SOURCE
  ////////////////////////////////////////////////////////////

  source?: {

    slug?: string;

    planet?: string;

    zodiacSign?: string;

  };

}


//////////////////////////////////////////////////////////////
// REMEDY INTELLIGENCE RESULT
//////////////////////////////////////////////////////////////
//
// Final result returned by the Remedy Engine.
//
// `available` tells downstream systems whether
// a valid remedy was resolved.
//
// `context` contains the already-known planetary
// influence used for resolution.
//
//////////////////////////////////////////////////////////////

export interface RemedyIntelligenceResult {

  /**
   * Resolved remedy, when available.
   */
  remedy?: ResolvedRemedy;

  /**
   * Whether a remedy was successfully resolved.
   */
  available: boolean;

  /**
   * Planetary context used by the resolver.
   */
  context?: RemedyContext;

}


//////////////////////////////////////////////////////////////
// END OF REMEDY INTELLIGENCE TYPES
//////////////////////////////////////////////////////////////